<a href="https://colab.research.google.com/github/teguhprastyopy/pythorch_fundamentals_exercise/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
torch.__version__

'1.13.1+cu116'

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [11]:
MATRIX = torch.tensor([[1, 2],
                       [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
random_tensor = torch.rand(size = (3,4))
random_tensor, random_tensor.dtype

(tensor([[0.4518, 0.6413, 0.0803, 0.5803],
         [0.1011, 0.8724, 0.3860, 0.7604],
         [0.5846, 0.6623, 0.3879, 0.2441]]), torch.float32)

In [19]:
random_image_size_tensor = torch.rand(size=(244,244,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

In [20]:
zeros = torch.zeros(size = (3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]), torch.float32)

In [21]:
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]), torch.float32)

In [22]:
zero_to_ten_deprecated = torch.range(0, 10)

zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

<ipython-input-22-7c87c37a9f0f>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,
                               device = None,
                               requires_grad = False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [25]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float16)
float_16_tensor.dtype

torch.float16

In [26]:
some_tensor = torch.rand(3,4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.1402, 0.1155, 0.4428, 0.6883],
        [0.7558, 0.3755, 0.1810, 0.5064],
        [0.6666, 0.8057, 0.4290, 0.1442]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [27]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [28]:
tensor * 10

tensor([10, 20, 30])

In [30]:
tensor

tensor([1, 2, 3])

In [31]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [32]:
tensor  = tensor + 10
tensor

tensor([1, 2, 3])

In [33]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [34]:
tensor

tensor([1, 2, 3])

In [35]:
print(tensor, "*", tensor)
print("Equals", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals tensor([1, 4, 9])


In [36]:
import torch
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [37]:
tensor * tensor

tensor([1, 4, 9])

In [38]:
torch.matmul(tensor,tensor)

tensor(14)

In [39]:
tensor @ tensor

tensor(14)

In [40]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.01 ms, sys: 966 µs, total: 1.97 ms
Wall time: 1.47 ms


tensor(14)

In [42]:
%%time 
torch.matmul(tensor, tensor)

CPU times: user 109 µs, sys: 5 µs, total: 114 µs
Wall time: 119 µs


tensor(14)

In [46]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]], dtype = torch.float32)

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]], dtype = torch.float32)

torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

In [47]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [49]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [50]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [51]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [52]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features = 2,
                         out_features = 6)

x = tensor_A
output =linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [53]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
print(f"min : {x.min()}")
print(f"max : {x.max()}")
# print(f"mean : {x.mean()}") klo yang ini error bro
print(f"mean : {x.type(torch.float32).mean()}") # gk ada float32, gk bisa
print(f"sum : {x.sum()}")

min : 0
max : 90
mean : 45.0
sum : 450


In [55]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [56]:
tensor = torch.arange(10, 100, 10)
print(f"tensor: {tensor}")

print(f"index max : {tensor.argmax()}")
print(f"index min : {tensor.argmin()}")

tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
index max : 8
index min : 0


In [57]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [58]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [59]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [60]:
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [61]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [62]:
z = x.view(1, 7)
z , z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [63]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [64]:
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [65]:
print(f"previous tensor: {x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nnew tensor : {x_squeezed}")
print(f"new shape : {x_squeezed.shape}")

previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
previous shape: torch.Size([1, 7])

new tensor : tensor([5., 2., 3., 4., 5., 6., 7.])
new shape : torch.Size([7])


In [66]:
print(f"previous tensor : {x_squeezed}")
print(f"previous shape : {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nnew tensor : {x_unsqueezed}")
print(f"new shape : {x_unsqueezed.shape}")

previous tensor : tensor([5., 2., 3., 4., 5., 6., 7.])
previous shape : torch.Size([7])

new tensor : tensor([[5., 2., 3., 4., 5., 6., 7.]])
new shape : torch.Size([1, 7])


In [68]:
x_original = torch.rand(size=(244,244,3))

x_permuted = x_original.permute(2,0,1)

print(f"previous shape : {x_original.shape}")
print(f"new shape : {x_permuted.shape}")

previous shape : torch.Size([244, 244, 3])
new shape : torch.Size([3, 244, 244])


In [69]:
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [70]:
print(f"1st square bracket :\n{x[0]}")
print(f"2nd square bracket : {x[0][0]}")
print(f"3rd square bracket : {x[0][0][0]}")

1st square bracket :
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2nd square bracket : tensor([1, 2, 3])
3rd square bracket : 1


In [71]:
x[:, 0]

tensor([[1, 2, 3]])

In [72]:
x[:, :, 0]

tensor([[1, 4, 7]])

In [73]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [74]:
x[:, 1, 1]

tensor([5])

In [75]:
x[0, 0, :]

tensor([1, 2, 3])